# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Coding Standards"

on:
    workflow_dispatch: null

permissions:
    contents: "write"
    pull-requests: "write"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    fix:
        name: "Fix"
        runs-on: "ubuntu-latest"
        steps:
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "8.2"
                coverage: "none"
        -
            name: "Checkout repository"
            uses: "actions/checkout@v4"
        -
            name: "Remove Laravel Nova"
            run: "composer remove --no-interaction --no-update laravel/nova"
        -
            name: "Install dependencies"
            run: "composer update --no-interaction"
        -
            name: "Fix violations"
            run: "composer exec -- pint -v"
        -
            name: "Check difference to repository"
            id: "list_diff"
            run: |
                if ! git diff --exit-code ':!:composer.json'; then
                    echo "exit_status=1" >>"${GITHUB_OUTPUT}"
                fi
        -
            name: "Create pull request"
            if: "${{ steps.list_diff.outputs.exit_status == '1' }}"
            uses: "peter-evans/create-pull-request@v6"
            with:
                add-paths: "./"
                branch: "cs-fixer"
                commit-message: "Fix CS"
                title: "Fix Coding Standards violations"
                body: |
                    Automated changes by running `pint`.
                delete-branch: true
